<a href="https://colab.research.google.com/github/Jay-hv7/DL-Practice/blob/main/dot_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# dot product between two vectors

In [2]:
vec1 = [1.0, 2.0, 3.0]
vec2 = [1.0, 2.0, 3.0]
dot_prod = np.dot(vec1, vec2)
print(dot_prod)

2.8


In [3]:
# change the order of dot product

In [4]:
dot_prod_reverse = np.dot(vec2, vec1)
print(dot_prod_reverse)

2.8


In [5]:
vec1 = [1.0, 2.0, 3.0]
vec2 = [0.2, 0.4, 0.6]
bias = 2.0
dot_prod = np.dot(vec1, vec2) + bias
dot_prod_reverse = np.dot(vec2, vec1) + bias

print(dot_prod)
print(dot_prod_reverse)

4.8
4.8


### np.dot(a,b) = np.dot(b,a) # dot product between vectors

# dot product between vector and matrix

In [8]:
input = [1.0, 2.0, 3.0] # (1,3)
w = [[1.0, 2.0, 3.0],    # (3,3)
        [1.0, 3.0, 2.0],
        [2.0, 2.0, 3.0]]
dot_prod = np.dot(input, w) # ---1,3
print(dot_prod)


[ 9. 14. 16.]


In [9]:
dot_prod_reverse = np.dot(w,input) # 3,3 X 1,3

[14. 13. 15.]


np.dot(vec,matrix) != np.dot(matrix,vec)




# dot product between matrix

In [13]:
in1 = [[1.0, 2.0, 3.0],    # (3,3)
        [2.0, 3.0, 4.0],
        [5.0, 6.0, 7.0]]
w = [[1.0, 2.0, 3.0],    # (3,3)
        [1.0, 3.0, 2.0],
        [2.0, 2.0, 3.0]]
dot_prod = np.dot(in1, w) # ---3,3
print(dot_prod)

[[ 9. 14. 16.]
 [13. 21. 24.]
 [25. 42. 48.]]


In [14]:
in1 = [[1.0, 2.0, 3.0],    # (3,3)
        [2.0, 3.0, 4.0],
        [5.0, 6.0, 7.0]]
w = [[1.0, 2.0, 3.0],    # (3,3)
        [1.0, 3.0, 2.0],
        [2.0, 2.0, 3.0]]
dot_prod_rev = np.dot(w,in1) # ---3,3
print(dot_prod_rev)

[[20. 26. 32.]
 [17. 23. 29.]
 [21. 28. 35.]]


### np.dot(matrix1, matrix2) != np.dot(matrix2,matrix1)