<a href="https://colab.research.google.com/github/Jay-hv7/DL-Practice/blob/main/Torch_Prerequisites.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
scalar = torch.tensor(2.0)
scalar

tensor(2.)

In [4]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [5]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
tensor3d = torch.tensor([
    [[1,2,3],[3,4,5]],
    [[5,8,9],[9,4,6]]
])
tensor3d

tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 8, 9],
         [9, 4, 6]]])

In [7]:
tensor3d.dtype

torch.int64

## setting datatype

In [8]:
vector = torch.tensor([1,2,3],dtype=torch.float32)
vector.dtype

torch.float32

### new tensors with predefined

In [9]:
ones = torch.ones([1,2,3])
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [10]:
z = torch.zeros([2,3])
z

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
z1 = torch.zeros_like(z)
z1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
full = torch.full((2,2,3),6)
full

tensor([[[6, 6, 6],
         [6, 6, 6]],

        [[6, 6, 6],
         [6, 6, 6]]])

In [13]:
Identity = torch.eye(3)
Identity

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## random values between 0 &1

In [14]:
random_tensor = torch.rand(3,2)
random_tensor

tensor([[0.8279, 0.3793],
        [0.9256, 0.2872],
        [0.8337, 0.7227]])

## random values from normal distribution

In [15]:
torch.randn(3,2)

tensor([[ 1.4213,  0.2790],
        [-1.3844,  0.8224],
        [-0.4102, -1.7482]])

## Shape type device

In [16]:
t = torch.randn(3,2)
print("tensor ",t)
print("shape ",t.shape)
print("ndim or Rank  ",t.ndim)
print("data type", t.dtype)
print("device ",t.device)
print("num of elements",t.numel())


tensor  tensor([[-0.9974, -0.6485],
        [-0.0281, -1.1946],
        [-0.7156, -0.2294]])
shape  torch.Size([3, 2])
ndim or Rank   2
data type torch.float32
device  cpu
num of elements 6


# move tensor to gpu

In [17]:
t_gpu = t.to('cuda')
print("device ",t_gpu.device)

device  cuda:0


## Torch methods

In [19]:
scalar = torch.tensor(4.0)
scalar.item() # works only for scalar

4.0

In [20]:
vec = torch.tensor([1,2,3,4])
vec.numpy()

array([1, 2, 3, 4])

## Memory sharing  of numpy Converted tensors

In [21]:
vec_numpy = vec.numpy()
vec_numpy[0] = 5
print(vec)

tensor([5, 2, 3, 4])


In [24]:
numpy_matrix = np.array([[1,2,3],[3,4,5]])
tensor_from_numpy = torch.from_numpy(numpy_matrix)
print("after copy ",tensor_from_numpy)
tensor_from_numpy[0][0] = 10
print("after modify tensor",tensor_from_numpy)
print("after modify numpy",numpy_matrix)

after copy  tensor([[1, 2, 3],
        [3, 4, 5]])
after modify tensor tensor([[10,  2,  3],
        [ 3,  4,  5]])
after modify numpy [[10  2  3]
 [ 3  4  5]]


### Usage tips
1. torch.tensor([1,2,3]) avoid torch.Tensor
2. All tensors need to be on the same device
3. Avoid explicit datatype fix if mixed tensor types are there
